In [1]:
import numpy as np
import random

# -----------------------------
# Simple GridWorld Environment
# -----------------------------
class GridWorld:
    def __init__(self, size=4):
        self.size = size
        self.start = (0, 0)
        self.goal = (size - 1, size - 1)
        self.reset()

    def reset(self):
        self.pos = self.start
        return self.pos

    def step(self, action):
        x, y = self.pos

        if action == 0:   # up
            x = max(0, x - 1)
        elif action == 1: # down
            x = min(self.size - 1, x + 1)
        elif action == 2: # left
            y = max(0, y - 1)
        elif action == 3: # right
            y = min(self.size - 1, y + 1)

        self.pos = (x, y)

        # Reward
        if self.pos == self.goal:
            return self.pos, 1, True  # reached goal
        else:
            return self.pos, 0, False  # no reward

# -----------------------------
# Q-Learning Algorithm
# -----------------------------
env = GridWorld(size=4)

# Q-table: 4x4 grid with 4 actions each
Q = np.zeros((4, 4, 4))

alpha = 0.1      # learning rate
gamma = 0.9      # discount factor
epsilon = 0.3    # exploration probability
episodes = 2000

for _ in range(episodes):
    state = env.reset()
    done = False

    while not done:
        x, y = state

        # Epsilon-greedy action selection
        if random.random() < epsilon:
            action = random.choice([0, 1, 2, 3])  # explore
        else:
            action = np.argmax(Q[x, y])           # exploit

        next_state, reward, done = env.step(action)
        nx, ny = next_state

        # Q-learning update rule
        Q[x, y, action] = Q[x, y, action] + alpha * (
            reward + gamma * np.max(Q[nx, ny]) - Q[x, y, action]
        )

        state = next_state

# -----------------------------
# Test the trained agent
# -----------------------------
state = env.reset()
done = False
path = [state]

print("Learned Q-values:")
print(Q)

while not done:
    x, y = state
    action = np.argmax(Q[x, y])
    state, reward, done = env.step(action)
    path.append(state)

print("\nPath taken by the agent:")
print(path)


Learned Q-values:
[[[5.31441000e-01 4.78296896e-01 5.31441000e-01 5.90490000e-01]
  [5.90490000e-01 6.49862524e-01 5.31441000e-01 6.56100000e-01]
  [6.56099999e-01 7.28988658e-01 5.90490000e-01 7.29000000e-01]
  [7.29000000e-01 8.10000000e-01 6.56100000e-01 7.29000000e-01]]

 [[5.31441000e-01 1.89061962e-01 4.43964393e-01 4.49574681e-01]
  [5.90490000e-01 3.76805066e-01 4.19962420e-01 7.28008878e-01]
  [6.56100000e-01 7.07157951e-01 5.99283149e-01 8.10000000e-01]
  [7.29000000e-01 9.00000000e-01 7.28999840e-01 8.10000000e-01]]

 [[3.75930431e-01 7.66303912e-03 8.38673729e-02 1.24469546e-01]
  [5.76261081e-01 7.17899640e-03 7.78764080e-02 9.75347758e-02]
  [7.28938211e-01 6.04113287e-01 3.23655012e-01 8.79724439e-01]
  [8.09999999e-01 1.00000000e+00 7.56486919e-01 8.99999989e-01]]

 [[8.36718629e-02 0.00000000e+00 0.00000000e+00 0.00000000e+00]
  [9.37212723e-02 0.00000000e+00 0.00000000e+00 0.00000000e+00]
  [7.53634317e-02 7.87194960e-04 2.63691719e-04 8.90581011e-01]
  [0.00000000e+0